--CREATE TABLE tb_worker (
--	id int8 GENERATED BY DEFAULT AS IDENTITY, 
--	name varchar(255), 
--	daily_income float8, 
--	PRIMARY KEY (id)
--	);

INSERT INTO tb_worker (name, daily_income) VALUES ('Adail Silva', 367.0);
INSERT INTO tb_worker (name, daily_income) VALUES ('Ágatha Silva', 300.0);
INSERT INTO tb_worker (name, daily_income) VALUES ('Davi Miguel', 250.0);
